# Generated by Django 5.2.17 on 2026-09-04 09:27

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_user_job_title_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('rank', models.PositiveIntegerField(default=10, help_text='Higher outranks lower. Used by has_role_at_least.')),
                ('is_system', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rank', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(db_index=True, max_length=64)),
                ('allowed', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.roledefinition')),
            ],
            options={
                'ordering': ['page_key'],
                'constraints': [models.UniqueConstraint(fields=('role', 'page_key'), name='uq_role_page')],
            },
        ),
    ]
