# Generated by Django 5.2.17 on 2026-09-04 06:47

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_ACTIVATED', 'User activated'), ('USER_DEACTIVATED', 'User deactivated'), ('USER_DELETED', 'User deleted'), ('ROLE_CHANGED', 'Role changed'), ('PASSWORD_RESET', 'Password reset'), ('PASSWORD_CHANGED', 'Password changed'), ('ADMIN_BOOTSTRAPPED', 'Administrator bootstrapped'), ('PROJECT_CREATED', 'Project created'), ('PROJECT_UPDATED', 'Project updated'), ('PROJECT_DELETED', 'Project deleted')], db_index=True, max_length=48)),
                ('actor_label', models.CharField(blank=True, max_length=254)),
                ('target', models.CharField(blank=True, max_length=254)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='ix_audit_action_time')],
            },
        ),
    ]
