# Generated by Django 5.2.17 on 2026-09-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('USER_CREATED', 'User created'), ('USER_UPDATED', 'User updated'), ('USER_ACTIVATED', 'User activated'), ('USER_DEACTIVATED', 'User deactivated'), ('USER_DELETED', 'User deleted'), ('ROLE_CHANGED', 'Role changed'), ('PASSWORD_RESET', 'Password reset'), ('PASSWORD_CHANGED', 'Password changed'), ('ADMIN_BOOTSTRAPPED', 'Administrator bootstrapped'), ('PROJECT_CREATED', 'Project created'), ('PROJECT_UPDATED', 'Project updated'), ('PROJECT_DELETED', 'Project deleted'), ('DEPARTMENT_CREATED', 'Department created'), ('DEPARTMENT_UPDATED', 'Department updated'), ('DEPARTMENT_DELETED', 'Department deleted')], db_index=True, max_length=48),
        ),
    ]
